# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Sep_martin_pena/Zybo-Z7-Master.xdc

# Block Designs: bd/Memorice_completo/Memorice_completo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo || ORIG_REF_NAME==Memorice_completo} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_Player_game_manager_0_0/Memorice_completo_Player_game_manager_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_Player_game_manager_0_0 || ORIG_REF_NAME==Memorice_completo_Player_game_manager_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_Sequence_display_0_0/Memorice_completo_Sequence_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_Sequence_display_0_0 || ORIG_REF_NAME==Memorice_completo_Sequence_display_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_debouncer_0_0/Memorice_completo_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_debouncer_0_0 || ORIG_REF_NAME==Memorice_completo_debouncer_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_SM_0_0/Memorice_completo_SM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_SM_0_0 || ORIG_REF_NAME==Memorice_completo_SM_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_RAM_sin_axi_0_0/Memorice_completo_RAM_sin_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_RAM_sin_axi_0_0 || ORIG_REF_NAME==Memorice_completo_RAM_sin_axi_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_rgb_driver_sin_axi_0_0/Memorice_completo_rgb_driver_sin_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_rgb_driver_sin_axi_0_0 || ORIG_REF_NAME==Memorice_completo_rgb_driver_sin_axi_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_ila_0_0/Memorice_completo_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_ila_0_0 || ORIG_REF_NAME==Memorice_completo_ila_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_vio_0_0/Memorice_completo_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_vio_0_0 || ORIG_REF_NAME==Memorice_completo_vio_0_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_or_btn_0/Memorice_completo_or_btn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_or_btn_0 || ORIG_REF_NAME==Memorice_completo_or_btn_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_or_reset_0/Memorice_completo_or_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_or_reset_0 || ORIG_REF_NAME==Memorice_completo_or_reset_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_debouncer_reset_0/Memorice_completo_debouncer_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_debouncer_reset_0 || ORIG_REF_NAME==Memorice_completo_debouncer_reset_0} -quiet] -quiet

# IP: bd/Memorice_completo/ip/Memorice_completo_slice_btn0_0/Memorice_completo_slice_btn0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memorice_completo_slice_btn0_0 || ORIG_REF_NAME==Memorice_completo_slice_btn0_0} -quiet] -quiet

# XDC: bd/Memorice_completo/Memorice_completo_ooc.xdc
