# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Sep_martin_pena/Zybo-Z7-Master.xdc

# Block Designs: bd/block_design_ayu_2_full/block_design_ayu_2_full.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ayu_2_full || ORIG_REF_NAME==block_design_ayu_2_full} -quiet] -quiet

# IP: bd/block_design_ayu_2_full/ip/block_design_ayu_2_full_RAM_0_2/block_design_ayu_2_full_RAM_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ayu_2_full_RAM_0_2 || ORIG_REF_NAME==block_design_ayu_2_full_RAM_0_2} -quiet] -quiet

# IP: bd/block_design_ayu_2_full/ip/block_design_ayu_2_full_ALU_0_1/block_design_ayu_2_full_ALU_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ayu_2_full_ALU_0_1 || ORIG_REF_NAME==block_design_ayu_2_full_ALU_0_1} -quiet] -quiet

# IP: bd/block_design_ayu_2_full/ip/block_design_ayu_2_full_SM_0_1/block_design_ayu_2_full_SM_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ayu_2_full_SM_0_1 || ORIG_REF_NAME==block_design_ayu_2_full_SM_0_1} -quiet] -quiet

# XDC: bd/block_design_ayu_2_full/block_design_ayu_2_full_ooc.xdc
