# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ALU_0_0/design_1_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ALU_0_0 || ORIG_REF_NAME==design_1_ALU_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAM2_0_0/design_1_RAM2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAM2_0_0 || ORIG_REF_NAME==design_1_RAM2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_prog_mem_0_0/design_1_prog_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_prog_mem_0_0 || ORIG_REF_NAME==design_1_prog_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_instr_mem_0_0/design_1_instr_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_instr_mem_0_0 || ORIG_REF_NAME==design_1_instr_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_control_unit_0_0/design_1_control_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_control_unit_0_0 || ORIG_REF_NAME==design_1_control_unit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
