# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/Sep_martin_pena/bloques_creados/alu/src/Zybo-Z7-Master.xdc

# Block Designs: bd/block_design_1/block_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1 || ORIG_REF_NAME==block_design_1} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_ALU_0_0/block_design_1_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_ALU_0_0 || ORIG_REF_NAME==block_design_1_ALU_0_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_SM_0_0/block_design_1_SM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_SM_0_0 || ORIG_REF_NAME==block_design_1_SM_0_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_RAM_0_0/block_design_1_RAM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_RAM_0_0 || ORIG_REF_NAME==block_design_1_RAM_0_0} -quiet] -quiet

# XDC: bd/block_design_1/block_design_1_ooc.xdc
